name: bitasa_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # Mantenemos la restricción flexible para ser compatibles con el entorno de CI/CD.
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  # La línea de 'intl' se elimina para evitar conflictos.

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- LÍNEA CORREGIDA ---
  # Bajamos la versión de flutter_lints a una que es compatible con el SDK de Dart 3.4.3.
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/