name: bitasa_web
description: "La mejor manera de calcular los cambios de tus bólivares."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  path_provider: ^2.1.2

  sembast: ^3.7.0
  sembast_web: ^2.3.0

  # --- AÑADIR ESTAS TRES LÍNEAS ---
  collection: ^1.18.0
  fl_chart: ^0.68.0
  scrollable_positioned_list: ^0.3.8

  table_calendar: ^3.1.2 # Calendario
  share_plus: ^9.0.0 # Compartir
  qr_flutter: ^4.1.0 # QR

  url_launcher: ^6.3.1 # Lanzar URLs
  showcaseview: ^3.0.0 # Tutorial interactivo
  shared_preferences: ^2.2.3 # Preferencias

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/