name: bitasa_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod:
  firebase_core:
  cloud_firestore:
  path_provider:
  
  # --- NUEVA DEPENDENCIA ---
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/