name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

permissions:
  contents: read # Damos permiso de lectura del contenido

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        # Nos aseguramos de que el build use la ruta base correcta para Firebase
        run: flutter build web --release --base-href /

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BITASA_V1 }}'
          channelId: live
          projectId: 'bitasa-v1'