name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Confiamos en que el canal estable nos dará la versión más reciente,
          # que debe incluir un SDK de Dart compatible.
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --web-renderer canvaskit --base-href /bitasa_web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web