name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Forzamos una versión numérica muy reciente para asegurar un SDK de Dart moderno.
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        # Eliminamos la opción '--web-renderer' para máxima compatibilidad,
        # y usamos '--release' para una construcción optimizada.
        run: flutter build web --release --base-href /bitasa_web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web